### POST request to register a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Mike Wazowski",
  "email": "mike@example.com",
  "address": "13 monster town, Monster verse",
  "dateOfBirth": "2001-01-24",
  "registeredDate": "2025-05-24"
}

###