### POST request to register a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Rishabh Shekhawat",
  "email": "shekhawat.rishabh@example.com",
  "address": "23 down town, jaipur",
  "dateOfBirth": "2003-01-03",
  "registeredDate": "2025-05-24"
}

###