### POST request to register a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Prashant Kala",
  "email": "prashant.kala@example.com",
  "address": "123 jaiput",
  "dateOfBirth": "2003-05-23",
  "registeredDate": "2025-05-17"
}

###